version: "3"

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: sales_db
    networks:
    - shared-network
    image: postgres:11.1-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
    - 5432:5432
  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411
